version: "2.4"


networks:

  web-net:
    driver: "bridge"


volumes:

  mattermost-config:
    driver: "local"

  mattermost-data:
    driver: "local"

  mattermost-postgres-data:
    driver: "local"


services:

  mattermost:
    build: "."
    image: "arvacims/mattermost:5.0.0"
    environment:
      - "DB_HOST=mattermost-postgres"
      - "DB_PORT_5432_TCP_PORT=5432"
      - "MM_USERNAME=mmuser"
      - "MM_PASSWORD=mmuser_password"
      - "MM_DBNAME=mattermost"
    ports:
      - "8000:8000/tcp"
    networks:
      - "web-net"
    volumes:
      - "mattermost-config:/mattermost/config"
      - "mattermost-data:/mattermost/data"
    mem_limit: "512m"
    restart: "on-failure"
    depends_on:
      - "mattermost-postgres"

  mattermost-postgres:
    image: "postgres:9.6.8-alpine"
    environment:
      - "POSTGRES_USER=mmuser"
      - "POSTGRES_PASSWORD=mmuser_password"
      - "POSTGRES_DB=mattermost"
    networks:
      - "web-net"
    volumes:
      - "mattermost-postgres-data:/var/lib/postgresql/data"
    mem_limit: "256m"
    restart: "on-failure"
